sonar.projectKey=ESGI-4AL-Microservice-Groupe14
sonar.projectName=ESGI-4AL-Microservice-Groupe14
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000

sonar.language=py
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

sonar.sources=services/main/restaurant-service,services/main/customer-service,services/main/shared

sonar.tests=services/tests

sonar.test.inclusions=**/test_*.py

sonar.exclusions=.venv/**,**/__pycache__/**,.idea/**,**/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
